BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `links` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`card_id`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL,
	`link`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `files` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`card_id`	INTEGER NOT NULL,
	`name`	TEXT NOT NULL,
	`file`	BLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS `card` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`title`	TEXT NOT NULL,
	`description`	TEXT NOT NULL,
	`image`	BLOB NOT NULL,
	`hidden`	INTEGER DEFAULT 1
);
COMMIT;
